# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='key',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
