# Generated by Django 1.11.18 on 2019-03-13 15:44


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('enrollments', '0002_program_org_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('role', models.CharField(choices=[('organization_read_metadata', 'Read Metadata Only'), ('organization_read_enrollments', 'Read Enrollments Data'), ('organization_read_write_enrollments', 'Read and Write Enrollments Data')], default='organization_read_metadata', max_length=255)),
            ],
            options={
                'verbose_name': 'Organization Group',
            },
            bases=('auth.group',),
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('organization_read_metadata', 'View Organization Metadata'), ('organization_read_enrollments', 'Read Organization enrollment data'), ('organization_write_enrollments', 'Read and Write Organization enrollment data'))},
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.Organization'),
        ),
    ]
