# Generated by Django 1.11.18 on 2019-03-13 20:49


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_organizationgroup'),
        ('enrollments', '0003_add_organization_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationgroup',
            name='group_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='organization_old', serialize=False, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='program',
            name='managing_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.Organization'),
        ),
    ]
