# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_add_org_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGroupFutureMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('membership_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('org_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_group_future_memberships', to='enrollments.OrgGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
