# Generated by Django 1.11.20 on 2019-05-06 22:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_remove_org_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallearner',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallearnerprogramenrollment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallearnerprogramenrollment',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='historicallearnerprogramenrollment',
            name='program',
        ),
        migrations.AlterUniqueTogether(
            name='learnerprogramenrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='learnerprogramenrollment',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='learnerprogramenrollment',
            name='program',
        ),
        migrations.DeleteModel(
            name='HistoricalLearner',
        ),
        migrations.DeleteModel(
            name='HistoricalLearnerProgramEnrollment',
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.DeleteModel(
            name='LearnerProgramEnrollment',
        ),
    ]
