# Generated by Django 1.11.20 on 2019-05-10 18:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_title_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
        migrations.RemoveField(
            model_name='program',
            name='url',
        ),
    ]
