""" Constants for enrollments app """
from enum import Enum


PROGRAM_ENROLLMENT_ENROLLED = 'enrolled'
PROGRAM_ENROLLMENT_PENDING = 'pending'
PROGRAM_ENROLLMENT_SUSPENDED = 'suspended'
PROGRAM_ENROLLMENT_CANCELED = 'canceled'

PROGRAM_ENROLLMENT_STATUSES = [
    PROGRAM_ENROLLMENT_ENROLLED,
    PROGRAM_ENROLLMENT_PENDING,
    PROGRAM_ENROLLMENT_SUSPENDED,
    PROGRAM_ENROLLMENT_CANCELED,
]

COURSE_ENROLLMENT_ACTIVE = 'active'
COURSE_ENROLLMENT_INACTIVE = 'inactive'

COURSE_ENROLLMENT_STATUSES = [
    COURSE_ENROLLMENT_ACTIVE,
    COURSE_ENROLLMENT_INACTIVE,
]

ENROLLMENT_ERROR_DUPLICATED = 'duplicated'
ENROLLMENT_ERROR_INTERNAL = 'internal-error'

LMS_ENROLLMENT_WRITE_MAX_SIZE = 25


class EnrollmentWriteStatus(Enum):
    OK = 200
    NO_CONTENT = 204
    MULTI_STATUS = 207
    UNPROCESSABLE_ENTITY = 422
