# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(editable=False)),
                ('original_url', models.URLField()),
                ('created', models.DateTimeField()),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Retrying', 'Retrying')], default='In Progress', max_length=11)),
                ('result_url', models.URLField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
