# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_organizationgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrganizationUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('organization_read_metadata', 'Read Metadata Only'), ('organization_read_enrollments', 'Read Enrollments Data'), ('organization_read_write_enrollments', 'Read and Write Enrollments Data')], default='organization_read_metadata', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
