# Generated by Django 1.11.18 on 2019-03-15 15:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_organizationgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('organization_read_metadata', 'View Organization Metadata'), ('organization_read_enrollments', 'Read Organization enrollment data'), ('organization_write_enrollments', 'Write Organization enrollment data'))},
        ),
    ]
