# Generated by Django 1.11.18 on 2019-03-20 13:17


from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_write_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUserOrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_email', models.EmailField(max_length=254)),
                ('organization_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OrganizationGroup')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='pendinguserorganizationgroup',
            unique_together={('user_email', 'organization_group')},
        ),
    ]
