# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_write_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('core.organization_read_metadata', 'View Organization Metadata'), ('core.organization_read_enrollments', 'Read Organization enrollment data'), ('core.organization_write_enrollments', 'Write Organization enrollment data'))},
        ),
    ]
