# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_new_program_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('read_metadata', 'View Organization Metadata'), ('read_enrollments', 'Read Organization enrollment data'), ('write_enrollments', 'Write Organization enrollment data'))},
        ),
        migrations.AlterField(
            model_name='organizationgroup',
            name='role',
            field=models.CharField(choices=[('read_metadata', 'Read Metadata Only'), ('read_enrollments', 'Read Enrollments Data'), ('read_write_enrollments', 'Read and Write Enrollments Data'), ('read_reports', 'Read Reports')], default='read_metadata', max_length=255),
        ),
    ]
