# Generated by Django 1.11.24 on 2019-12-16 20:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_new_program_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('organization_read_metadata', 'View Metadata'), ('organization_read_enrollments', 'Read enrollment data'), ('organization_write_enrollments', 'Write enrollment data'), ('read_reports', 'Read reports data'))},
        ),
        migrations.AlterField(
            model_name='organizationgroup',
            name='role',
            field=models.CharField(choices=[('organization_read_metadata', 'Read Metadata Only'), ('organization_read_enrollments', 'Read Enrollments Data'), ('organization_read_write_enrollments', 'Read and Write Enrollments Data'), ('read_reports', 'Read Reports')], default='organization_read_metadata', max_length=255),
        ),
    ]
