# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_program_move'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='program',
            table=None,
        ),
    ]
