# Generated by Django 2.2.12 on 2020-04-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pending_user_organization_group_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryProgram',
            fields=[
            ],
            options={
                'indexes': [],
                'constraints': [],
                'proxy': True,
            },
            bases=('core.program',),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
