# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_pending_user_organization_group_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_course_role_management',
            field=models.BooleanField(default=False),
        ),
    ]
