# Generated by Django 2.2.12 on 2020-06-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tweaks_for_django_22'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='key',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
