# Generated by Django 2.2.13 on 2020-06-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_validate_slug_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscoveryProgram',
        ),
    ]
