name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - 3.8
        toxenv: [ django32 ]
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Set display to virtual frame buffer
      run: export DISPLAY=:99.0
    - name: Install dependencies
      run: |
        pip install -U pip wheel
        make requirements
    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: make validate
    - name: Make Static and Validate Translations
      env:
        TOXENV: ${{ matrix.toxenv }}
        DJANGO_SETTINGS_MODULE: registrar.settings.test
      run: |
        sudo apt install gettext
        make static
        make validate_translations
    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='django32'
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true
